on:
  schedule:
    - cron:  '0 * * * *'
name: Pull 3 Hours Ago
jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: ./cli.js hour "$(date --date="3 hours ago")"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
