on:
  schedule:
    - cron:  '10 * * * *'
name: Pull Data and Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        entrypoint: npm
        args: install
    - name: Pull
      uses: mikeal/npx@master
      with:
        entrypoint: node
        args: cli.js action
      env:
        GHTOKEN: ${{ secrets.GHTOKEN }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
